version: 2
formats: all
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: requirements/pip.txt
    - requirements: requirements/docs.txt

search:
  ranking:
    # was able to move it down with -5
    api/v1.html: -2
    api/v2.html: 0
    api/v3.html: 0
