version: 2
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: requirements/pip.txt
    - requirements: requirements/docs.txt

search:
  ranking:
    api/v1.html: 0
    api/v2.html: 0
    api/v3.html: 5
